# see http://pre-commit.com/#usage and run `pre-commit --help` for more info
# To update these hooks, run `pre-commit autoupdate` and commit the changes.
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 17478a0a50faf20fd8e5b3fefe7435cea410df0b
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
-   repo: git@github.com:pre-commit/mirrors-jshint
    sha: 0b547c64213cc0dda0aa8e6b420a38a356d51e7a
    hooks:
    -   id: jshint
        language_version: 4.2.6
-   repo: git@github.com:pre-commit/mirrors-eslint
    sha: 02999128135512d63e07d4a8a05d424cde3fe5d1
    hooks:
    -   id: eslint
        args:
        - --quiet
        language_version: 4.2.6
-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: f840ac610d8d9d76b666062416241f2156b3f388
    hooks:
    -   id: scss-lint
-   repo: git@github.com:elidupuis/mirrors-jscs.git
    sha: 0be04381d2541c98f7c874aaa9cb988ba963b77e
    hooks:
    -   id: jscs
        language_version: 4.2.6
