# see http://pre-commit.com/#usage and run `pre-commit --help` for more info
# To update these hooks, run `pre-commit autoupdate` and commit the changes.
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/prettier/prettier
    sha: 1.11.0
    hooks:
      - id: prettier
        args:
          - --loglevel=silent
        # ignoring HTML files as Prettier's support is still experimental
        # https://github.com/prettier/prettier/blob/1.10.2/.pre-commit-hooks.yaml#L6
        files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx)$
  - repo: git@github.com:pre-commit/mirrors-eslint
    sha: v4.10.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-plugin-ember
        args:
          - --fix
          - --quiet
        language_version: 6.9.4
