# see http://pre-commit.com/#usage and run `pre-commit --help` for more info
# To update these hooks, run `pre-commit autoupdate` and commit the changes.
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 64943e86417774b9d6ba63c74e00f8cc3e2119e0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
-   repo: git@github.com:pre-commit/mirrors-jshint
    sha: c62c18f8ed2a43ef47483a1e0677fc532d228d73
    hooks:
    -   id: jshint
        language_version: 4.2.4
-   repo: git@github.com:pre-commit/mirrors-eslint
    sha: aaa8651ac4833f38c66a6b1b475856f4b1e01c57
    hooks:
    -   id: eslint
        args:
        - --quiet
        language_version: 4.2.4
-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: f840ac610d8d9d76b666062416241f2156b3f388
    hooks:
    -   id: scss-lint
-   repo: git@github.com:elidupuis/mirrors-jscs.git
    sha: c32a15eac3e747f363d8fa3ed274ad3be83cf965
    hooks:
    -   id: jscs
        language_version: 4.2.4
