# see http://pre-commit.com/#usage and run `pre-commit --help` for more info
# To update these hooks, run `pre-commit autoupdate` and commit the changes.
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: e626cd57090d8df0be21e4df0f4e55cc3511d6ab
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
-   repo: git@github.com:pre-commit/mirrors-eslint
    sha: v3.14.0
    hooks:
    -   id: eslint
        additional_dependencies:
        - eslint
        - eslint-plugin-ember-suave
        args:
        - --quiet
        language_version: 6.9.4
-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
