# See https://github.com/brigade/scss-lint
# Linter rule listing: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:
  BemDepth:
    enabled: true
  LeadingZero:
    style: include_zero
  NestingDepth:
    ignore_parent_selectors: true
  # https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt
  # https://smacss.com/book/formatting
  PropertySortOrder:
    order: smacss
  # http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/
  SelectorFormat:
    convention: hyphenated_BEM
  UnnecessaryParentReference:
    exclude:
      - '**/*/styles.scss' # so ember-component-css pod `style.scss` won't blow up
